---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      # - software-properties-common # FIXME: broken for now https://www.reddit.com/r/debian/comments/1n9aakj/why_were_the_softwareproperties_tools_removed/
      - curl
      - ca-certificates
      - apt-transport-https
    state: present
    update_cache: true

- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add CRI-O repository GPG key
  ansible.builtin.shell:
    cmd:
      set -e -o pipefail &&
      curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/Release.key |
      gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
    executable: /bin/bash
  args:
    creates: /etc/apt/keyrings/cri-o-apt-keyring.gpg

- name: Add CRI-O repository
  ansible.builtin.shell:
    cmd:
      set -e -o pipefail &&
      echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/{{ crio_version }}/deb/ /" |
      tee /etc/apt/sources.list.d/cri-o.list
    executable: /bin/bash
  register: output
  changed_when: output.rc != 0 # TODO: Check if this is correct

- name: Install CRI-O
  ansible.builtin.apt:
    name: cri-o
    state: present
    update_cache: true

- name: Enable and start CRI-O service
  ansible.builtin.systemd:
    name: crio
    enabled: true
    state: started
