---
- name: Add Kubernetes repository GPG key
  ansible.builtin.shell:
    cmd:
      set -e -o pipefail &&
      curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key |
      gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    executable: /bin/bash
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repository
  ansible.builtin.shell:
    cmd:
      set -e -o pipefail &&
      echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /" |
      tee /etc/apt/sources.list.d/kubernetes.list
    executable: /bin/bash
  register: output
  changed_when: output.rc != 0 # TODO: check if this is correct

- name: Install kubeadm, kubelet, and optionally kubectl
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ kubernetes_components }}"

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: started
